export const theme = {
  colors: {
    background: "var(--color-background)",
    foreground: "var(--color-foreground)",
    primary: "var(--color-primary)",
    primaryDark: "var(--color-primary-dark)",
    primaryText: "var(--color-primary-text)",
    secondaryText: "var(--color-secondary-text)",
    mutedText: "var(--color-muted-text)",
    accent: "var(--color-accent)",
    accentYellow: "var(--color-accent-yellow)",
    surface: "var(--color-surface)",
    surfaceMuted: "var(--color-surface-muted)",
    surfaceSoft: "var(--color-surface-soft)",
    border: "var(--color-border)",
    borderStrong: "var(--color-border-strong)",
    borderSoft: "var(--color-border-soft)",
    white: "var(--color-white)",
  },
  space: {
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    14: "3.5rem",
    16: "4rem",
  },
  radius: {
    md: "0.375rem",
    lg: "0.5rem",
    xl: "0.75rem",
  },
  shadow: {
    sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
  },
  breakpoint: {
    sm: "640px",
    md: "768px",
    lg: "1024px",
  },
  transition: "150ms ease",
} as const;
